/* eslint-disable @typescript-eslint/no-require-imports */
const { Client } = require("pg")
require("dotenv").config()

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim()
    .slice(0, 100)
}

const RECIPES = [
  {
    title: "Sinigang na Baboy",
    description: "A comforting sour soup made with pork ribs, tamarind, and fresh vegetables. Perfect for rainy days.",
    story: "My lola would make this every Friday after the palengke. The smell of sinigang simmering meant the whole family was coming over.",
    category: "soup",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 15,
    cookTime: 60,
    servings: 6,
    tags: ["budget", "sabaw", "family-favorite", "comfort-food"],
    ingredients: [
      { name: "Pork ribs (buto-buto)", amount: "1", unit: "kg", notes: "cut into serving pieces" },
      { name: "Tamarind sinigang mix", amount: "1", unit: "pack", notes: "or 2 cups fresh tamarind juice" },
      { name: "Kangkong (water spinach)", amount: "1", unit: "bunch" },
      { name: "String beans (sitaw)", amount: "1", unit: "cup", notes: "cut into 2-inch pieces" },
      { name: "Eggplant (talong)", amount: "1", unit: "medium", notes: "sliced diagonally" },
      { name: "Radish (labanos)", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Okra", amount: "6", unit: "pieces", notes: "tops removed" },
      { name: "Tomato", amount: "2", unit: "medium", notes: "quartered" },
      { name: "Onion", amount: "1", unit: "medium", notes: "quartered" },
      { name: "Ginger", amount: "1", unit: "thumb-sized", notes: "smashed" },
      { name: "Fish sauce (patis)", amount: "2", unit: "tbsp" },
      { name: "Green chili (siling haba)", amount: "3", unit: "pieces" },
      { name: "Water", amount: "8", unit: "cups" },
    ],
    steps: [
      { number: 1, instruction: "In a large pot, boil water with onion, tomato, and ginger." },
      { number: 2, instruction: "Add pork ribs and simmer for 45 minutes or until tender. Skim off scum as needed.", tips: "Low heat gives clearer broth" },
      { number: 3, instruction: "Add sinigang mix or tamarind juice. Stir well." },
      { number: 4, instruction: "Add radish and cook for 3 minutes." },
      { number: 5, instruction: "Add string beans, eggplant, okra, and green chili. Cook for 3 minutes." },
      { number: 6, instruction: "Season with fish sauce to taste." },
      { number: 7, instruction: "Add kangkong, turn off heat, and cover for 2 minutes.", tips: "Don't overcook the kangkong — residual heat is enough" },
      { number: 8, instruction: "Serve hot with steamed rice." },
    ],
  },
  {
    title: "Adobong Manok",
    description: "The national dish of the Philippines — chicken simmered in soy sauce, vinegar, garlic, and bay leaves.",
    story: "Every family has their own adobo. Ours is dark, garlicky, and a little oily — the way my tatay liked it.",
    category: "ulam",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    tags: ["classic", "budget", "family-favorite", "no-fuss"],
    ingredients: [
      { name: "Chicken legs and thighs", amount: "1", unit: "kg", notes: "bone-in, skin-on" },
      { name: "Soy sauce (toyo)", amount: "1/2", unit: "cup" },
      { name: "White vinegar (suka)", amount: "1/3", unit: "cup" },
      { name: "Garlic", amount: "6", unit: "cloves", notes: "crushed" },
      { name: "Bay leaves (laurel)", amount: "3", unit: "pieces" },
      { name: "Black peppercorns", amount: "1", unit: "tsp" },
      { name: "Cooking oil", amount: "2", unit: "tbsp" },
      { name: "Water", amount: "1/2", unit: "cup" },
      { name: "Sugar", amount: "1", unit: "tsp", notes: "optional, to balance" },
    ],
    steps: [
      { number: 1, instruction: "Combine chicken, soy sauce, garlic, bay leaves, and peppercorns. Marinate for 30 minutes (or overnight for deeper flavor).", tips: "The longer you marinate, the saltier the adobo" },
      { number: 2, instruction: "Heat oil in a pot over medium heat. Add the chicken pieces (reserve the marinade) and sear until lightly browned on all sides." },
      { number: 3, instruction: "Pour in the reserved marinade and water. Bring to a boil." },
      { number: 4, instruction: "Add vinegar. DO NOT STIR. Let it boil uncovered for 5 minutes.", tips: "Don't stir after adding vinegar — it prevents the raw vinegar taste from cooking off" },
      { number: 5, instruction: "Cover, lower heat, and simmer for 25-30 minutes until chicken is tender." },
      { number: 6, instruction: "Season with sugar if desired. Adjust saltiness with more soy sauce." },
      { number: 7, instruction: "Serve with steamed rice. The sauce is best when poured generously over rice." },
    ],
  },
  {
    title: "Kare-Kare",
    description: "A rich peanut stew with oxtail, tripe, and vegetables. Served with bagoong on the side.",
    story: "Kare-kare was saved for special occasions because oxtail was expensive. My lola would wake up at 5AM to start cooking it for fiesta.",
    category: "fiesta",
    region: "kapampangan",
    difficulty: "hard",
    prepTime: 30,
    cookTime: 180,
    servings: 8,
    tags: ["special-occasion", "fiesta", "party", "rich"],
    ingredients: [
      { name: "Oxtail", amount: "1", unit: "kg", notes: "cut into 2-inch segments" },
      { name: "Beef tripe (goto)", amount: "300", unit: "g", notes: "cleaned and sliced" },
      { name: "Peanut butter", amount: "1", unit: "cup", notes: "smooth" },
      { name: "Annatto seeds (atsuete)", amount: "2", unit: "tbsp", notes: "soaked in 1/4 cup warm water" },
      { name: "Eggplant", amount: "2", unit: "medium", notes: "grilled or fried" },
      { name: "String beans", amount: "1", unit: "cup" },
      { name: "Banana blossom (puso ng saging)", amount: "1", unit: "cup", notes: "sliced" },
      { name: "Peanut powder", amount: "1/2", unit: "cup" },
      { name: "Onion", amount: "1", unit: "medium", notes: "chopped" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Bagoong alamang", amount: "1/2", unit: "cup", notes: "for serving" },
      { name: "Rice flour", amount: "2", unit: "tbsp", notes: "for thickening" },
    ],
    steps: [
      { number: 1, instruction: "Boil oxtail and tripe in a large pot for 2 hours until very tender. Reserve 6 cups of broth." },
      { number: 2, instruction: "Sauté onion and garlic in oil until fragrant." },
      { number: 3, instruction: "Add annatto water — this gives the signature orange-red color." },
      { number: 4, instruction: "Pour in reserved broth. Add peanut butter and peanut powder. Stir until dissolved.", tips: "Use smooth peanut butter for creamier sauce" },
      { number: 5, instruction: "Add cooked oxtail and tripe. Simmer for 15 minutes." },
      { number: 6, instruction: "Thicken with rice flour mixed in cold water. Stir continuously." },
      { number: 7, instruction: "Add vegetables. Cook for 3 minutes." },
      { number: 8, instruction: "Serve hot with generous amount of bagoong alamang on the side." },
    ],
  },
  {
    title: "Pork Sisig",
    description: "A sizzling chopped pork dish with calamansi, chili, and onion — iconic Kapampangan pulutan.",
    story: "Sisig was born in Angeles City, Pampanga. My uncle would order it with ice-cold beer after work — the sizzling plate was always the star.",
    category: "ulam",
    region: "kapampangan",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    tags: ["pulutan", "sizzling", "popular", "party"],
    ingredients: [
      { name: "Pork face (maskara)", amount: "500", unit: "g", notes: "boiled and grilled" },
      { name: "Pork ears", amount: "200", unit: "g" },
      { name: "Chicken liver", amount: "100", unit: "g" },
      { name: "Onion", amount: "1", unit: "medium", notes: "finely chopped" },
      { name: "Calamansi", amount: "3", unit: "pieces", notes: "juice extracted" },
      { name: "Green chili (siling pang-sigang)", amount: "3", unit: "pieces", notes: "chopped" },
      { name: "Red chili", amount: "2", unit: "pieces", notes: "optional, for heat" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Mayonnaise", amount: "2", unit: "tbsp" },
      { name: "Butter", amount: "1", unit: "tbsp" },
      { name: "Egg", amount: "1", unit: "piece" },
    ],
    steps: [
      { number: 1, instruction: "Boil pork face and ears for 45 minutes until tender. Drain and grill until skin is crispy." },
      { number: 2, instruction: "Grill chicken liver separately until just cooked through." },
      { number: 3, instruction: "Finely chop all grilled meats into small cubes.", tips: "The finer the chop, the better the sisig texture" },
      { number: 4, instruction: "In a bowl, combine chopped meat with calamansi juice, soy sauce, and chopped onions." },
      { number: 5, instruction: "Heat a sizzling plate or cast iron pan. Melt butter." },
      { number: 6, instruction: "Add the sisig mixture. Crack an egg on top and let it cook on the hot plate." },
      { number: 7, instruction: "Add chopped chilies, top with mayonnaise, and serve immediately while sizzling." },
    ],
  },
  {
    title: "Chicken Tinola",
    description: "A light and ginger-forward chicken soup with green papaya and malunggay leaves.",
    story: "Tinola was always the go-to when someone was sick. My nanay believed the ginger would heal everything — and honestly, it always worked.",
    category: "soup",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    tags: ["sabaw", "healthy", "comfort-food", "ginger"],
    ingredients: [
      { name: "Chicken", amount: "1", unit: "kg", notes: "cut into serving pieces" },
      { name: "Green papaya", amount: "1", unit: "medium", notes: "peeled and sliced into wedges" },
      { name: "Malunggay leaves", amount: "1", unit: "cup", notes: "or dahon ng sili as substitute" },
      { name: "Ginger", amount: "1", unit: "large thumb", notes: "cut into strips" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Water", amount: "6", unit: "cups" },
      { name: "Cooking oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Sauté ginger in oil until fragrant — about 2 minutes. Then add garlic and onion.", tips: "Let the ginger really cook — it releases more flavor" },
      { number: 2, instruction: "Add chicken pieces and cook until lightly browned on all sides." },
      { number: 3, instruction: "Add fish sauce and cook for 1 minute." },
      { number: 4, instruction: "Pour in water and bring to a boil. Lower heat and simmer for 20 minutes." },
      { number: 5, instruction: "Add green papaya and cook for 5 minutes until soft but not mushy." },
      { number: 6, instruction: "Turn off heat. Add malunggay leaves and let residual heat cook them." },
      { number: 7, instruction: "Serve hot with steamed rice." },
    ],
  },
  {
    title: "Bicol Express",
    description: "A fiery pork stew cooked in coconut milk with shrimp paste and loads of siling labuyo.",
    story: "Bicolanos know their gata. This dish was named after the train from Manila to Bicol — just as hot and intense as the Bicol sun.",
    category: "ulam",
    region: "bicol",
    difficulty: "medium",
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    tags: ["spicy", "gata", "bicol", "creamy"],
    ingredients: [
      { name: "Pork belly (liempo)", amount: "500", unit: "g", notes: "cut into strips" },
      { name: "Coconut milk (gata)", amount: "2", unit: "cups", notes: "first press" },
      { name: "Coconut cream (kakang gata)", amount: "1/2", unit: "cup", notes: "for topping" },
      { name: "Shrimp paste (bagoong alamang)", amount: "3", unit: "tbsp" },
      { name: "Green chili (siling haba)", amount: "6", unit: "pieces", notes: "sliced" },
      { name: "Red chili (siling labuyo)", amount: "5", unit: "pieces", notes: "chopped, adjust to taste" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "chopped" },
      { name: "Ginger", amount: "1", unit: "thumb", notes: "julienned" },
    ],
    steps: [
      { number: 1, instruction: "Sauté garlic, onion, and ginger until fragrant.", tips: "Don't burn the garlic — it will make the dish bitter" },
      { number: 2, instruction: "Add pork belly and cook until browned." },
      { number: 3, instruction: "Add bagoong and cook for 2 minutes to develop flavor." },
      { number: 4, instruction: "Pour in coconut milk and bring to a simmer. Cook for 20 minutes until pork is tender and oil starts to separate." },
      { number: 5, instruction: "Add green chilies and half the labuyo. Simmer for 5 minutes." },
      { number: 6, instruction: "Pour in coconut cream. Add remaining labuyo. Simmer for 3 minutes.", tips: "Adding coconut cream at the end gives that rich, creamy finish" },
      { number: 7, instruction: "Serve with steamed rice. The sauce is addictive — make sure you have extra rice." },
    ],
  },
  {
    title: "Lechon Kawali",
    description: "Deep-fried crispy pork belly with a crackling skin that shatters when you bite into it.",
    story: "My tito would make this for Noche Buena — the sizzling sound of pork hitting hot oil meant Christmas had truly begun.",
    category: "ulam",
    region: "tagalog",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 60,
    servings: 6,
    tags: ["crispy", "party", "fiesta", "indulgent"],
    ingredients: [
      { name: "Pork belly (liempo)", amount: "1", unit: "kg", notes: "whole slab" },
      { name: "Garlic powder", amount: "1", unit: "tsp" },
      { name: "Salt", amount: "2", unit: "tbsp" },
      { name: "Peppercorns", amount: "1", unit: "tsp" },
      { name: "Bay leaves", amount: "3", unit: "pieces" },
      { name: "Water", amount: "4", unit: "cups" },
      { name: "Cooking oil", amount: "4", unit: "cups", notes: "for deep frying" },
    ],
    steps: [
      { number: 1, instruction: "In a pot, combine pork belly, water, salt, peppercorns, bay leaves, and garlic powder. Boil for 45 minutes until tender." },
      { number: 2, instruction: "Remove pork and pat dry with paper towels. Let it cool completely.", tips: "The drier the skin, the crispier the result" },
      { number: 3, instruction: "Score the skin with a sharp knife in a crosshatch pattern. Rub salt deep into the cuts." },
      { number: 4, instruction: "Refrigerate uncovered for at least 1 hour (or overnight for best results).", tips: "This dries out the skin — essential for crackling" },
      { number: 5, instruction: "Heat oil in a deep pot. Carefully lower the pork skin-side down.", tips: "Cover the pot — the oil will splatter violently!" },
      { number: 6, instruction: "Fry until golden brown and the skin is puffed and crispy, about 8-10 minutes." },
      { number: 7, instruction: "Let rest for 5 minutes before chopping into serving pieces." },
      { number: 8, instruction: "Serve with lechon sauce (Mang Tomas) or soy vinegar dip." },
    ],
  },
  {
    title: "Pancit Canton",
    description: "A stir-fried noodle dish with meat, vegetables, and soy sauce — always present at Filipino birthday tables.",
    story: "Pancit means long life — so every birthday party had to have it. My lola would make a huge batch in her biggest kawali.",
    category: "ulam",
    region: "tagalog",
    difficulty: "medium",
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    tags: ["birthday", "noodles", "party", "stir-fry"],
    ingredients: [
      { name: "Pancit canton noodles", amount: "500", unit: "g", notes: "dried" },
      { name: "Chicken breast", amount: "200", unit: "g", notes: "sliced thin" },
      { name: "Pork", amount: "200", unit: "g", notes: "sliced thin" },
      { name: "Shrimp", amount: "150", unit: "g", notes: "peeled" },
      { name: "Carrot", amount: "1", unit: "medium", notes: "julienned" },
      { name: "Cabbage (repolyo)", amount: "2", unit: "cups", notes: "shredded" },
      { name: "Snap peas (snow peas)", amount: "1", unit: "cup" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Soy sauce", amount: "3", unit: "tbsp" },
      { name: "Oyster sauce", amount: "2", unit: "tbsp" },
      { name: "Calamansi", amount: "3", unit: "pieces" },
      { name: "Chicken broth", amount: "1", unit: "cup" },
      { name: "Cooking oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Soak pancit canton noodles in warm water for 10 minutes until softened. Drain and set aside." },
      { number: 2, instruction: "Sauté garlic and onion in oil. Add chicken and pork, cook until browned." },
      { number: 3, instruction: "Add shrimp and cook until pink." },
      { number: 4, instruction: "Pour in soy sauce, oyster sauce, and chicken broth. Bring to a boil." },
      { number: 5, instruction: "Add noodles and toss to coat evenly with the sauce. Cook for 3 minutes.", tips: "Use two spatulas to toss — it's easier than one" },
      { number: 6, instruction: "Add vegetables (carrots, cabbage, snap peas). Toss and cook for 2 minutes — vegetables should still have crunch." },
      { number: 7, instruction: "Squeeze calamansi on top and toss one more time." },
      { number: 8, instruction: "Serve hot, topped with sliced calamansi and a drizzle of soy sauce." },
    ],
  },
  {
    title: "Lumpiang Shanghai",
    description: "Crispy golden spring rolls filled with seasoned ground pork, shrimp, and vegetables.",
    story: "Every family gathering started with a tray of lumpia — the unofficial Filipino appetizer. We'd fight over the crispy edges.",
    category: "merienda",
    region: "tagalog",
    difficulty: "medium",
    prepTime: 30,
    cookTime: 20,
    servings: 8,
    tags: ["appetizer", "party", "crispy", "kids-love-it"],
    ingredients: [
      { name: "Ground pork", amount: "500", unit: "g" },
      { name: "Shrimp", amount: "150", unit: "g", notes: "finely chopped" },
      { name: "Carrot", amount: "1", unit: "medium", notes: "finely minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "finely chopped" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Spring roll wrappers (lumpia wrapper)", amount: "30", unit: "pieces", notes: "thawed" },
      { name: "Egg", amount: "1", unit: "piece", notes: "beaten (for sealing)" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
      { name: "Cooking oil", amount: "3", unit: "cups", notes: "for deep frying" },
    ],
    steps: [
      { number: 1, instruction: "Combine ground pork, chopped shrimp, carrot, onion, garlic, soy sauce, salt, and pepper. Mix well." },
      { number: 2, instruction: "Take a lumpia wrapper and place about 1 tablespoon of filling near one edge.", tips: "Don't overfill or they'll burst while frying" },
      { number: 3, instruction: "Roll tightly, folding in the sides like a burrito. Seal the edge with beaten egg." },
      { number: 4, instruction: "Repeat with all filling. You can freeze the uncooked lumpia at this point." },
      { number: 5, instruction: "Heat oil to 350°F (medium-high). Deep fry in batches until golden brown, about 4-5 minutes." },
      { number: 6, instruction: "Drain on paper towels. Serve with sweet chili sauce or banana ketchup." },
    ],
  },
  {
    title: "Arroz Caldo",
    description: "A warm chicken rice porridge with ginger, garlic, and safflower. Filipino comfort in a bowl.",
    story: "When it rained, my lola would make arroz caldo. She said the ginger would keep us from getting sick — and a drizzle of calamansi made everything better.",
    category: "breakfast",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    tags: ["breakfast", "comfort-food", "ginger", "sabaw", "sick-day"],
    ingredients: [
      { name: "Glutinous rice (malagkit)", amount: "1", unit: "cup", notes: "rinsed" },
      { name: "Chicken thighs", amount: "400", unit: "g", notes: "bone-in" },
      { name: "Ginger", amount: "1", unit: "large thumb", notes: "julienned" },
      { name: "Garlic", amount: "6", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "chopped" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Safflower (kasubha)", amount: "1", unit: "pinch", notes: "for color" },
      { name: "Water", amount: "6", unit: "cups" },
      { name: "Toasted garlic (for topping)", amount: "2", unit: "tbsp" },
      { name: "Green onions", amount: "2", unit: "stalks", notes: "sliced" },
      { name: "Calamansi", amount: "2", unit: "pieces", notes: "for serving" },
      { name: "Hard-boiled egg", amount: "2", unit: "pieces", notes: "optional, sliced" },
    ],
    steps: [
      { number: 1, instruction: "Sauté ginger, garlic, and onion in oil until fragrant.", tips: "Toast the garlic really well — it's the star flavor" },
      { number: 2, instruction: "Add chicken pieces and cook until lightly browned." },
      { number: 3, instruction: "Add fish sauce and stir for 30 seconds." },
      { number: 4, instruction: "Pour in water and rice. Bring to a boil, then lower heat and simmer for 30 minutes, stirring occasionally.", tips: "Stir frequently to prevent the rice from sticking to the bottom" },
      { number: 5, instruction: "Remove chicken pieces. Shred the meat and return to the pot." },
      { number: 6, instruction: "Add kasubha and stir. The porridge should be thick and creamy." },
      { number: 7, instruction: "Serve in bowls. Top with toasted garlic, green onions, sliced egg, and a squeeze of calamansi." },
    ],
  },
  {
    title: "Chicken Inasal",
    description: "Grilled chicken marinated in calamansi, lemongrass, and annatto — a Bacolod specialty.",
    story: "Inasal from Bacolod is different — it's marinated with sinamak (spiced coconut vinegar) and grilled over hot coals. The best part? The chicken oil (sinamak) drizzled on rice.",
    category: "ulam",
    region: "visayas",
    difficulty: "medium",
    prepTime: 120,
    cookTime: 25,
    servings: 4,
    tags: ["grilled", "bacolod", "visayas", "party"],
    ingredients: [
      { name: "Chicken legs and thighs", amount: "1", unit: "kg" },
      { name: "Calamansi juice", amount: "1/3", unit: "cup" },
      { name: "Lemongrass (tanglad)", amount: "2", unit: "stalks", notes: "pounded" },
      { name: "Annatto oil (atsuete oil)", amount: "1/4", unit: "cup" },
      { name: "Garlic", amount: "5", unit: "cloves", notes: "minced" },
      { name: "Ginger", amount: "1", unit: "thumb", notes: "grated" },
      { name: "Brown sugar", amount: "2", unit: "tbsp" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Coconut vinegar", amount: "2", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Combine calamansi juice, lemongrass, annatto oil, garlic, ginger, sugar, fish sauce, and vinegar. Mix well." },
      { number: 2, instruction: "Marinate chicken for at least 2 hours (overnight is best).", tips: "The longer the marinade, the deeper the flavor" },
      { number: 3, instruction: "Grill over charcoal if possible. Baste with leftover marinade mixed with annatto oil while grilling.", tips: "Charcoal gives the authentic smoky inasal flavor" },
      { number: 4, instruction: "Cook each side for 12-15 minutes until charred but juicy inside." },
      { number: 5, instruction: "Serve with garlic rice (sinangag) and sinamak (spiced vinegar) dipping sauce." },
    ],
  },
  {
    title: "Beef Caldereta",
    description: "A rich tomato-based beef stew with liver spread, bell peppers, and chili — Kapampangan comfort.",
    story: "Caldereta was my ninong's specialty. He added liver spread and a touch of sugar — his secret for that rich, sweet-savory balance.",
    category: "ulam",
    region: "kapampangan",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    tags: ["rich", "party", "beef", "tomato"],
    ingredients: [
      { name: "Beef chuck (kalamnan)", amount: "1", unit: "kg", notes: "cubed" },
      { name: "Tomato sauce", amount: "1", unit: "cup" },
      { name: "Tomato paste", amount: "3", unit: "tbsp" },
      { name: "Liver spread", amount: "1/4", unit: "cup" },
      { name: "Potato", amount: "2", unit: "medium", notes: "cubed and fried" },
      { name: "Carrot", amount: "1", unit: "medium", notes: "cubed" },
      { name: "Red bell pepper", amount: "1", unit: "piece", notes: "sliced" },
      { name: "Green bell pepper", amount: "1", unit: "piece", notes: "sliced" },
      { name: "Green peas", amount: "1/2", unit: "cup" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "chopped" },
      { name: "Bay leaves", amount: "2", unit: "pieces" },
      { name: "Beef broth", amount: "2", unit: "cups" },
      { name: "Cooking oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Sauté garlic and onion. Add beef and sear until browned on all sides." },
      { number: 2, instruction: "Add bay leaves, tomato sauce, tomato paste, and beef broth. Bring to a boil." },
      { number: 3, instruction: "Lower heat, cover, and simmer for 1.5 hours until beef is very tender.", tips: "Add more broth if it dries up — you want a thick sauce, not dry" },
      { number: 4, instruction: "Add liver spread and stir until fully dissolved into the sauce.", tips: "Liver spread is the secret to caldereta's richness — don't skip it" },
      { number: 5, instruction: "Add carrots and cook for 5 minutes." },
      { number: 6, instruction: "Add fried potatoes, bell peppers, and green peas. Cook for 3 minutes." },
      { number: 7, instruction: "Season with salt and pepper to taste. Serve with steamed rice." },
    ],
  },
  {
    title: "Tinolang Isda (Fish Tinola)",
    description: "A light and sour fish soup with ginger, vegetables, and malunggay — common in coastal fishing communities.",
    story: "My grandfather was a fisherman in Quezon. He'd come home with the morning catch and my lola would make tinolang isda in 20 minutes flat.",
    category: "soup",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    tags: ["fish", "healthy", "sabaw", "quick", "seafood"],
    ingredients: [
      { name: "Fresh fish (bangus or tilapia)", amount: "1", unit: "kg", notes: "cleaned, sliced" },
      { name: "Ginger", amount: "1", unit: "large thumb", notes: "julienned" },
      { name: "Green papaya", amount: "1", unit: "medium", notes: "sliced into wedges" },
      { name: "Malunggay leaves", amount: "1", unit: "cup" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Calamansi juice", amount: "2", unit: "tbsp" },
      { name: "Water", amount: "4", unit: "cups" },
    ],
    steps: [
      { number: 1, instruction: "Sauté ginger, garlic, and onion in oil until fragrant." },
      { number: 2, instruction: "Add fish sauce and cook for 30 seconds." },
      { number: 3, instruction: "Pour in water and bring to a boil." },
      { number: 4, instruction: "Add green papaya and cook for 5 minutes." },
      { number: 5, instruction: "Gently add fish. Do not stir — let it simmer for 8 minutes.", tips: "Don't stir or the fish will break apart" },
      { number: 6, instruction: "Add malunggay leaves and calamansi juice. Turn off heat." },
      { number: 7, instruction: "Serve immediately with steamed rice." },
    ],
  },
  {
    title: "Ube Halaya",
    description: "A sweet and creamy purple yam dessert — the quintessential Filipino甜蜜 treat.",
    story: "Making ube halaya was a family affair. Everyone took turns grating the purple yam while my lola stirred the pot for hours.",
    category: "dessert",
    region: "tagalog",
    difficulty: "medium",
    prepTime: 20,
    cookTime: 45,
    servings: 8,
    tags: ["dessert", "ube", "sweet", "fiesta", "christmas"],
    ingredients: [
      { name: "Purple yam (ube)", amount: "1", unit: "kg", notes: "boiled and grated" },
      { name: "Coconut milk (gata)", amount: "2", unit: "cups" },
      { name: "Condensed milk", amount: "1", unit: "can", notes: "397g" },
      { name: "Butter", amount: "1/2", unit: "cup" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Sugar", amount: "1/2", unit: "cup", notes: "adjust to taste" },
    ],
    steps: [
      { number: 1, instruction: "Boil ube until fork-tender. Grate finely or mash until smooth.", tips: "The smoother the mash, the creamier the halaya" },
      { number: 2, instruction: "In a large pan, combine coconut milk and condensed milk. Heat over medium-low." },
      { number: 3, instruction: "Add grated ube and butter. Stir continuously.", tips: "Constant stirring prevents burning — this takes patience" },
      { number: 4, instruction: "Add vanilla and sugar. Keep stirring until the mixture thickens and pulls away from the pan (about 30-40 minutes)." },
      { number: 5, instruction: "Pour into a greased dish. Smooth the top with a spatula." },
      { number: 6, instruction: "Let cool completely before slicing. Refrigerate for at least 2 hours." },
      { number: 7, instruction: "Serve as is or top with grated cheese for the classic combo." },
    ],
  },
  {
    title: "Ginataang Manok",
    description: "Chicken simmered in coconut milk with green papaya, ginger, and chili — a Bicol region staple.",
    story: "In Bicol, every dish has gata. My tita would add so much siling labuyo your ears would sweat — but you couldn't stop eating.",
    category: "ulam",
    region: "bicol",
    difficulty: "medium",
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    tags: ["gata", "bicol", "spicy", "creamy"],
    ingredients: [
      { name: "Chicken", amount: "1", unit: "kg", notes: "cut into serving pieces" },
      { name: "Coconut milk (gata)", amount: "2", unit: "cups" },
      { name: "Green papaya", amount: "1", unit: "medium", notes: "sliced into wedges" },
      { name: "Ginger", amount: "1", unit: "thumb", notes: "julienned" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Red chili (siling labuyo)", amount: "4", unit: "pieces", notes: "chopped" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Malunggay leaves", amount: "1", unit: "cup" },
    ],
    steps: [
      { number: 1, instruction: "Sauté ginger, garlic, and onion until aromatic." },
      { number: 2, instruction: "Add chicken and cook until lightly browned." },
      { number: 3, instruction: "Pour in coconut milk and add fish sauce. Bring to a gentle simmer." },
      { number: 4, instruction: "Add green papaya and cook for 15 minutes until chicken is tender." },
      { number: 5, instruction: "Add chilies and malunggay. Simmer for 3 more minutes." },
      { number: 6, instruction: "Serve hot with rice. The sauce is best when it's slightly oily from the coconut." },
    ],
  },
  {
    title: "Tapsilog",
    description: "The ultimate Filipino breakfast — cured beef tapa, garlic fried rice, and fried egg.",
    story: "Tapsilog is not just food — it's a mood. After a long night or an early morning, a plate of tapsilog fixes everything.",
    category: "breakfast",
    region: "tagalog",
    difficulty: "medium",
    prepTime: 60,
    cookTime: 15,
    servings: 4,
    tags: ["breakfast", "silog", "beef", "garlic-rice"],
    ingredients: [
      { name: "Beef sirloin (kabilugan)", amount: "500", unit: "g", notes: "thinly sliced" },
      { name: "Soy sauce", amount: "1/4", unit: "cup" },
      { name: "Calamansi juice", amount: "1/4", unit: "cup" },
      { name: "Garlic", amount: "5", unit: "cloves", notes: "minced" },
      { name: "Brown sugar", amount: "2", unit: "tbsp" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Day-old rice", amount: "4", unit: "cups" },
      { name: "Toasted garlic (for rice)", amount: "3", unit: "tbsp" },
      { name: "Egg", amount: "4", unit: "pieces" },
      { name: "Cooking oil", amount: "3", unit: "tbsp" },
      { name: "Vinegar", amount: "1/2", unit: "cup", notes: "for dipping sauce" },
      { name: "Green chili", amount: "2", unit: "pieces", notes: "for dipping sauce" },
    ],
    steps: [
      { number: 1, instruction: "Marinate beef with soy sauce, calamansi juice, garlic, brown sugar, and pepper for at least 1 hour.", tips: "Overnight marination makes the tapa sweeter and more tender" },
      { number: 2, instruction: "For the sinangag (garlic rice): heat oil, fry toasted garlic until golden. Add day-old rice and toss. Season with salt." },
      { number: 3, instruction: "Cook the tapa: fry marinated beef in a hot pan until edges are crispy, about 3-4 minutes per side." },
      { number: 4, instruction: "Fry eggs sunny-side up in a separate pan." },
      { number: 5, instruction: "Make dipping sauce: combine vinegar, minced garlic, siling labuyo, and salt." },
      { number: 6, instruction: "Plate: rice first, topped with tapa, egg on the side. Serve with vinegar dipping sauce." },
    ],
  },
  {
    title: "Laing",
    description: "Dried taro leaves (gabi) cooked in coconut milk with chili — a Bicol classic.",
    story: "Laing is proof that Bicolanos can make anything taste good with gata and sili. My lola dried the gabi leaves herself under the sun.",
    category: "ulam",
    region: "bicol",
    difficulty: "medium",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    tags: ["gata", "bicol", "spicy", "vegetarian-option"],
    ingredients: [
      { name: "Dried taro leaves (dahon ng gabi)", amount: "50", unit: "g", notes: "rehydrated" },
      { name: "Coconut milk (gata)", amount: "2", unit: "cups" },
      { name: "Coconut cream (kakang gata)", amount: "1/2", unit: "cup" },
      { name: "Pork belly", amount: "200", unit: "g", notes: "sliced thin (optional)" },
      { name: "Red chili (siling labuyo)", amount: "5", unit: "pieces", notes: "whole or chopped" },
      { name: "Garlic", amount: "4", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Shrimp paste (bagoong)", amount: "2", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Soak dried taro leaves in water for 10 minutes. Drain." },
      { number: 2, instruction: "In a pot, combine coconut milk, garlic, onion, and bagoong. Bring to a gentle simmer." },
      { number: 3, instruction: "Add pork belly (if using) and cook for 10 minutes." },
      { number: 4, instruction: "Layer the taro leaves on top. DO NOT STIR. Cover and cook for 20 minutes.", tips: "Don't stir while cooking — the leaves need to absorb the coconut milk without breaking apart" },
      { number: 5, instruction: "Add chilies and coconut cream. Gently fold in. Cook for 5 more minutes." },
      { number: 6, instruction: "When oil starts to separate from the coconut milk, it's ready. Serve with rice." },
    ],
  },
  {
    title: "Halo-Halo",
    description: "The iconic Filipino shaved ice dessert with sweet beans, fruits, leche flan, ube, and ice cream.",
    story: "No summer is complete without halo-halo. My lola would set up a halo-halo station in the garage — everyone mixed their own.",
    category: "dessert",
    region: "tagalog",
    difficulty: "easy",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    tags: ["dessert", "summer", "fiesta", "no-cook"],
    ingredients: [
      { name: "Shaved ice", amount: "4", unit: "cups" },
      { name: "Ube halaya (purple yam jam)", amount: "1/2", unit: "cup" },
      { name: "Leche flan", amount: "4", unit: "slices" },
      { name: "Sweetened saba bananas", amount: "1/2", unit: "cup", notes: "sliced" },
      { name: "Sweetened langka (jackfruit)", amount: "1/2", unit: "cup", notes: "shredded" },
      { name: "Red munggo (red beans)", amount: "1/2", unit: "cup", notes: "sweetened" },
      { name: "Macapuno (coconut sport)", amount: "1/4", unit: "cup" },
      { name: "Nata de coco", amount: "1/4", unit: "cup" },
      { name: "Evaporated milk", amount: "1/2", unit: "cup" },
      { name: "Ube ice cream", amount: "4", unit: "scoops" },
      { name: "Pinipig (toasted rice flakes)", amount: "2", unit: "tbsp" },
    ],
    steps: [
      { number: 1, instruction: "Prepare all sweetened ingredients in separate bowls." },
      { number: 2, instruction: "In a tall glass, add a spoonful of each sweet ingredient at the bottom: ube, beans, macapuno, nata, langka, saba." },
      { number: 3, instruction: "Fill the glass with shaved ice, packing it tightly." },
      { number: 4, instruction: "Drizzle evaporated milk over the ice." },
      { number: 5, instruction: "Top with a slice of leche flan, a scoop of ube ice cream, and a sprinkle of pinipig." },
      { number: 6, instruction: "Serve with a long spoon — mix everything together before eating!", tips: "The key is mixing — every spoonful should have a bit of everything" },
    ],
  },
  {
    title: "Dinuguan",
    description: "A rich savory blood stew made with pork meat and innards, served with puto (rice cakes).",
    story: "Don't let the name scare you — dinuguan is pure comfort. My lola said the secret was patience: slow cooking until the blood turns rich and velvety.",
    category: "ulam",
    region: "tagalog",
    difficulty: "hard",
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    tags: ["traditional", "rich", "party", "innards"],
    ingredients: [
      { name: "Pork blood (dinugo)", amount: "500", unit: "ml", notes: "fresh" },
      { name: "Pork belly", amount: "300", unit: "g", notes: "cubed" },
      { name: "Pork heart", amount: "1", unit: "piece", notes: "chopped" },
      { name: "Pork intestines", amount: "200", unit: "g", notes: "cleaned and sliced" },
      { name: "Garlic", amount: "5", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "chopped" },
      { name: "Ginger", amount: "1", unit: "thumb", notes: "julienned" },
      { name: "Long green chili (siling haba)", amount: "4", unit: "pieces" },
      { name: "Vinegar", amount: "1/4", unit: "cup" },
      { name: "Bay leaves", amount: "2", unit: "pieces" },
      { name: "Sugar", amount: "1", unit: "tbsp" },
      { name: "Salt and pepper", amount: "to taste" },
      { name: "Puto (rice cakes)", amount: "6", unit: "pieces", notes: "for serving" },
    ],
    steps: [
      { number: 1, instruction: "Sauté garlic, onion, and ginger until fragrant." },
      { number: 2, instruction: "Add pork belly, heart, and intestines. Cook until browned." },
      { number: 3, instruction: "Add 2 cups water, bay leaves, and salt. Simmer for 30 minutes until meats are tender." },
      { number: 4, instruction: "Stir in the pork blood slowly, stirring constantly to prevent curdling.", tips: "Constant stirring prevents the blood from curdling — patience is key" },
      { number: 5, instruction: "Add vinegar and sugar. Simmer for 15 minutes on low heat until the sauce thickens." },
      { number: 6, instruction: "Add whole green chilies. Cook for 2 more minutes." },
      { number: 7, instruction: "Season with pepper. Serve hot with puto — the sweetness of puto balances the savory blood stew." },
    ],
  },
  {
    title: "Puto Bumbong",
    description: "A purple steamed rice cake traditionally served during Christmas, topped with coconut and muscovado.",
    story: "Simbang Gabi wasn't complete without puto bumbong. The steam rising from the bamboo tubes smelled like Christmas morning.",
    category: "dessert",
    region: "tagalog",
    difficulty: "hard",
    prepTime: 480,
    cookTime: 20,
    servings: 10,
    tags: ["christmas", "tradition", "simbang-gabi", "dessert"],
    ingredients: [
      { name: "Glutinous purple rice (pirurutong)", amount: "2", unit: "cups", notes: "soaked overnight" },
      { name: "Regular glutinous rice (malagkit)", amount: "1", unit: "cup", notes: "soaked overnight" },
      { name: "Grated coconut (niyog)", amount: "1", unit: "cup", notes: "fresh" },
      { name: "Muscovado sugar", amount: "1/2", unit: "cup", notes: "grated" },
      { name: "Butter or margarine", amount: "1/4", unit: "cup" },
      { name: "Salt", amount: "1/4", unit: "tsp" },
      { name: "Banana leaves", amount: "for wrapping", notes: "cut into squares" },
      { name: "Bamboo tubes (bumbong)", amount: "10", unit: "pieces", notes: "optional" },
    ],
    steps: [
      { number: 1, instruction: "Drain soaked rice. Grind or blend into a smooth, thick batter. Add salt." },
      { number: 2, instruction: "Line bamboo tubes with banana leaves. Fill with rice batter." },
      { number: 3, instruction: "Steam for 15-20 minutes until cooked through.", tips: "Traditional method uses bamboo tubes, but you can also use a regular steamer with banana leaf wrappers" },
      { number: 4, instruction: "Remove from tubes while hot. Spread butter onto each puto bumbong." },
      { number: 5, instruction: "Roll in grated muscovado sugar and top with fresh coconut." },
      { number: 6, instruction: "Serve warm with salabat (ginger tea) for the full Simbang Gabi experience." },
    ],
  },
  {
    title: "Pinakbet",
    description: "A classic Ilocano vegetable dish with shrimp paste, bitter melon, and squash — no water added.",
    story: "Ilocano cooking is about letting vegetables speak for themselves. No water, just bagoong and the natural juices of the vegetables.",
    category: "vegetable",
    region: "ilocano",
    difficulty: "easy",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    tags: ["vegetable", "ilocano", "healthy", "budget", "low-carb"],
    ingredients: [
      { name: "Bitter melon (ampalaya)", amount: "1", unit: "medium", notes: "sliced, seeds removed" },
      { name: "Squash (kalabasa)", amount: "1", unit: "cup", notes: "cubed" },
      { name: "String beans (sitaw)", amount: "1", unit: "cup", notes: "cut into 2-inch pieces" },
      { name: "Eggplant (talong)", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Okra", amount: "6", unit: "pieces", notes: "tops removed" },
      { name: "Pork belly", amount: "200", unit: "g", notes: "sliced thin (optional)" },
      { name: "Shrimp paste (bagoong isda)", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves", notes: "minced" },
      { name: "Onion", amount: "1", unit: "medium", notes: "sliced" },
      { name: "Ginger", amount: "1", unit: "thumb", notes: "smashed" },
      { name: "Tomato", amount: "2", unit: "medium", notes: "chopped" },
    ],
    steps: [
      { number: 1, instruction: "Sauté garlic, onion, ginger, and tomato in oil until soft." },
      { number: 2, instruction: "Add pork belly (if using) and cook until browned." },
      { number: 3, instruction: "Add bagoong and cook for 2 minutes.", tips: "Ilocano bagoong is fish-based, not shrimp — it has a distinct flavor" },
      { number: 4, instruction: "Add squash first (takes longest to cook). Cover and cook for 5 minutes. No water needed — the vegetables release their own juices." },
      { number: 5, instruction: "Add string beans, okra, and ampapaya. Cook for 3 minutes." },
      { number: 6, instruction: "Add ampalaya and eggplant last. Cook for 2 minutes — ampalaya should still have a slight crunch." },
      { number: 7, instruction: "Serve immediately. Traditional Ilocano pinakbet is dry — not soupy." },
    ],
  },
]

async function seed() {
  const client = new Client({
    connectionString: process.env.DATABASE_URL,
    statement_timeout: 30000,
    query_timeout: 30000,
  })

  await client.connect()
  console.log("Connected to database")

  // Find an existing user to be the author, or use first user
  const users = await client.query('SELECT id FROM "User" LIMIT 1')
  let authorId = null
  if (users.rows.length > 0) {
    authorId = users.rows[0].id
    console.log(`Using author: ${authorId}`)
  } else {
    console.log("No users found — recipes will have null author")
  }

  let seeded = 0
  let skipped = 0

  for (const recipe of RECIPES) {
    const slug = slugify(recipe.title)

    // Check if slug already exists
    const existing = await client.query('SELECT id FROM "Recipe" WHERE slug = $1', [slug])
    if (existing.rows.length > 0) {
      console.log(`Skipped: ${recipe.title} (already exists)`)
      skipped++
      continue
    }

    await client.query(
      `INSERT INTO "Recipe" (slug, title, description, story, category, region, difficulty, "prepTime", "cookTime", servings, ingredients, steps, tags, "authorId", "sourceType", "isPublished", "isFeatured", "viewCount", "cookCount", "createdAt", "updatedAt")
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12::jsonb, $13, $14, 'heirloom', true, false, 0, 0, NOW(), NOW())`,
      [
        slug,
        recipe.title,
        recipe.description,
        recipe.story,
        recipe.category,
        recipe.region,
        recipe.difficulty,
        recipe.prepTime,
        recipe.cookTime,
        recipe.servings,
        JSON.stringify(recipe.ingredients),
        JSON.stringify(recipe.steps),
        recipe.tags,
        authorId,
      ]
    )

    seeded++
    console.log(`Seeded: ${recipe.title}`)
  }

  console.log(`\nDone! ${seeded} new recipes, ${skipped} skipped`)
  await client.end()
}

seed().catch((e) => {
  console.error("Seed failed:", e.message)
  process.exit(1)
})
